import type { Metadata } from 'next'
import { kiwi_maru } from './fonts'
import './globals.css'
import { Providers } from './providers'
import { Header } from '@/app/_components/Layout/Header'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={kiwi_maru.className}>
        <Providers>
          <Header />
          <main className="mx-auto">{children}</main>
        </Providers>
      </body>
    </html>
  )
}
